### ISSUE TITLE
input and output structures are changed so need to incorporate that.

### ISSUE THREAD

**Issue by pkrajanand** [pkrajanand/TransformTree#6]
**Input**
```
groups:
  projects:
    - project-abc
  datacenter:
    - dc-1
  environments:
    - dev
    - test

hosts:
  node1.project-abc.dc-1.dev.com:
    vars:
      var1: 123
      var2: 456
    groups:
      - project-abc
      - dc-1
      - dev
      
  node2.project-abc.dc-1.dev.com:
    vars:
      var1: 123
      var2: 456
    groups:
      - project-abc
      - dc-1
      - dev
```

**Output**
```
{
  "project-abc": {
    "hosts": [
      "node1.project-abc.dc-1.dev.com",
      "node2.project-abc.dc-1.dev.com"
    ]
  },
  "dc-1": {
    "hosts": [
      "node1.project-abc.dc-1.dev.com",
      "node2.project-abc.dc-1.dev.com"
    ]
  },
  "dev": {
    "hosts": [
      "node1.project-abc.dc-1.dev.com",
      "node2.project-abc.dc-1.dev.com"
    ]
  },
  "projects": {
    "hosts": [
      "node1.project-abc.dc-1.dev.com",
      "node2.project-abc.dc-1.dev.com"
    ]
  },
  "datacenter": {
    "hosts": [
      "node1.project-abc.dc-1.dev.com",
      "node2.project-abc.dc-1.dev.com"
    ]
  },
  "environments": {
    "hosts": [
      "node1.project-abc.dc-1.dev.com",
      "node2.project-abc.dc-1.dev.com"
    ]
  },
  "_meta": {
    "hostvars": {
      "node1.project-abc.dc-1.dev.com": {
        "var1": 123,
        "var2": 456
      },
      "node2.project-abc.dc-1.dev.com": {
        "var1": 123,
        "var2": 456
      }
    }
  }
}
```
